//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Ecole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etudiant
    {
        public int ID_etudiant { get; set; }
        public int ID_groupe { get; set; }
        public string Prenom { get; set; }
        public string Nom { get; set; }
        public System.DateTime Date_naissance { get; set; }
    
        public virtual Grp_etudiant Grp_etudiant { get; set; }
    }
}
