//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Ecole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Helper
    {
        public string ID { get; set; }
        public int VALUE { get; set; }
    }
}
